// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Data;

#nullable disable

namespace QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009082453_SuaKhoaNgoaiLopHocVaChuongTrinhDaoTaodotnet")]
    partial class SuaKhoaNgoaiLopHocVaChuongTrinhDaoTaodotnet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Property<int>("MaChuongTrinhDaoTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuongTrinhDaoTao"));

                    b.Property<string>("EmailLienHe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TenChuongTrinhDaoTao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaChuongTrinhDaoTao");

                    b.HasIndex("TenChuongTrinhDaoTao")
                        .IsUnique();

                    b.ToTable("ChuongTrinhDaoTaos");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.HoSoDangKyHoc", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("HocVienMaHocVien")
                        .HasColumnType("int");

                    b.Property<int?>("LopHocMaLop")
                        .HasColumnType("int");

                    b.Property<string>("LyDoDangKy")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXetXetDuyet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHoSo");

                    b.HasIndex("HocVienMaHocVien");

                    b.HasIndex("LopHocMaLop");

                    b.ToTable("HoSoDangKyHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.HocVien", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MucTieuHoc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("SoThangDaHoc")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("TrinhDoHienTai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHocVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.KetQuaXepLop", b =>
                {
                    b.Property<int>("MaKetQuaXepLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQuaXepLop"));

                    b.Property<double?>("DiemDanhGia")
                        .HasColumnType("float");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MaKetQuaXepLop");

                    b.HasIndex("MaHoSo")
                        .IsUnique();

                    b.ToTable("KetQuaXepLops");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.LichKiemTraDauVao", b =>
                {
                    b.Property<int>("MaLichKiemTraDauVao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichKiemTraDauVao"));

                    b.Property<string>("DiaDiemHoacLienKet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GiaoVienKiemTra")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhThucKiemTra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HoSoDangKyHocMaHoSo")
                        .HasColumnType("int");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLichKiemTraDauVao");

                    b.HasIndex("HoSoDangKyHocMaHoSo");

                    b.ToTable("LichKiemTraDauVaos");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<double>("DiemDauVao")
                        .HasColumnType("float");

                    b.Property<DateTime>("HanDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaChuongTrinhDaoTao")
                        .HasColumnType("int");

                    b.Property<string>("MoTaLopHoc")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NgayBatDauDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrinhDoDauVao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YeuCauHocVien")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaChuongTrinhDaoTao");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.HoSoDangKyHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.HocVien", "HocVien")
                        .WithMany("HoSoDangKyHocs")
                        .HasForeignKey("HocVienMaHocVien")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.LopHoc", "LopHoc")
                        .WithMany("hoSoDangKyHoc")
                        .HasForeignKey("LopHocMaLop")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HocVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.HocVien", b =>
                {
                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("HocVien")
                        .HasForeignKey("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.HocVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.KetQuaXepLop", b =>
                {
                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.HoSoDangKyHoc", "HoSoDangKyHoc")
                        .WithOne("KetQuaXepLop")
                        .HasForeignKey("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.KetQuaXepLop", "MaHoSo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoSoDangKyHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.LichKiemTraDauVao", b =>
                {
                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.HoSoDangKyHoc", "HoSoDangKyHoc")
                        .WithMany("LichKiemTraDauVaos")
                        .HasForeignKey("HoSoDangKyHocMaHoSo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HoSoDangKyHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.LopHoc", b =>
                {
                    b.HasOne("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.ChuongTrinhDaoTao", "ChuongTrinhDaoTao")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaChuongTrinhDaoTao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuongTrinhDaoTao");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.HoSoDangKyHoc", b =>
                {
                    b.Navigation("KetQuaXepLop");

                    b.Navigation("LichKiemTraDauVaos");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.HocVien", b =>
                {
                    b.Navigation("HoSoDangKyHocs");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.LopHoc", b =>
                {
                    b.Navigation("hoSoDangKyHoc");
                });

            modelBuilder.Entity("QuanLyKhoaHoc_UNETI4_DHTI17A3HN.Models.TaiKhoan", b =>
                {
                    b.Navigation("HocVien");
                });
#pragma warning restore 612, 618
        }
    }
}
